language: cpp

dist: focal

addons:
  apt:
    packages:
      - qt5-default

env:
  jobs:
    - BUILD_CONFIGURATION=Release
    - BUILD_CONFIGURATION=Debug

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION ..
  - cmake --build .
