language: cpp

dist: bionic

before_install:
  - sudo apt update
  - sudo apt install -y qt5-default

env:
  - BUILD_CONFIGURATION=Release
  - BUILD_CONFIGURATION=Debug

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION .
  - cmake --build .
  - ctest --verbose
