version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Install packages
          command: >
            apt-get update &&
            apt-get -y dist-upgrade &&
            apt-get -y install git cmake build-essential qt5-default
      - run:
          name: Update submodules
          command: >
            mkdir -p ~/.ssh &&
            touch ~/.ssh/known_hosts &&
            ssh-keyscan github.com >> ~/.ssh/known_hosts &&
            git submodule update --init --recursive
      - run:
          name: Build muPDF library
          command: >
            export CFLAGS="-fPIC" &&
            cd lib/mupdf/ &&
            make HAVE_X11=no HAVE_GLUT=no -j `nproc` libs
      - run:
          name: Build
          command: >
            mkdir cmake &&
            cd cmake &&
            cmake -DCMAKE_BUILD_TYPE=Release .. &&
            make -j `nproc`
      - run:
          name: Test
          command: >
            cd cmake &&
            ctest -V
