version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Install packages
          command: >
            apt-get update &&
            apt-get -y dist-upgrade &&
            apt-get -y install git cmake g++ qt5-default
      - run:
          name: Build
          command: >
            mkdir cmake &&
            cd cmake &&
            cmake ../ &&
            cmake --build .
      - run:
          name: Test
          command: >
            cd cmake &&
            ctest -V

